'use client';
import { useState } from 'react';
import { ArrowRight, Compass, MapPinned, ShieldCheck } from 'lucide-react';
import { chairs } from '@/data/chairs';
import { Chair } from '@/types/chair';
import Header from '@/components/Header';
import ChairImage from '@/components/ChairImage';
import MapView from '@/components/MapView';
import ChairList from '@/components/ChairList';
import RestChatbot from '@/components/RestChatbot';

export default function Page() {
  const [page, setPage] = useState('home'); const [selected, setSelected] = useState<Chair | null>(null); const [building, setBuilding] = useState('본관'); const [floor, setFloor] = useState('1층');
  const openMap = (chair: Chair) => { setBuilding(chair.building); setFloor(chair.floor); setSelected(chair); setPage('map'); };
  return <><Header active={page} onNavigate={(p) => { setPage(p); if (p !== 'map') setSelected(null); }} />{page === 'home' && <Home onNavigate={setPage} onOpenMap={openMap} />}{page === 'map' && <MapView chairs={chairs.filter(c => c.building === building && c.floor === floor)} selected={selected} onSelect={setSelected} building={building} floor={floor} setBuilding={setBuilding} setFloor={setFloor} />}{page === 'list' && <ChairList chairs={chairs} onOpenMap={openMap} />}{page === 'about' && <About />}{page !== 'home' && <Footer />}<RestChatbot onOpenMap={openMap} /></>;
}

function Home({ onNavigate, onOpenMap }: { onNavigate: (p: string) => void; onOpenMap: (c: Chair) => void }) { const featured = chairs[0]; return <main><section className="container grid gap-10 py-14 md:grid-cols-[1.05fr_.95fr] md:items-center md:py-24"><div><div className="mb-5 inline-flex items-center gap-2 rounded-full bg-teal-50 px-3 py-1.5 text-xs font-extrabold text-teal-700"><Compass size={15} /> 병원 안 작은 쉼표</div><h1 className="max-w-xl text-4xl font-black leading-[1.18] tracking-tight md:text-6xl">병원 안에서<br /><span className="text-[#1668c7]">편히 쉴 수 있는 의자</span>를<br />찾아보세요.</h1><p className="mt-6 max-w-lg text-base leading-7 text-slate-600">진료와 이동 사이, 잠시 숨을 고를 수 있는 휴식 공간을 건물별·층별 약도에서 쉽게 찾아볼 수 있어요.</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={() => onNavigate('map')} className="flex items-center gap-2 rounded-xl bg-[#1668c7] px-5 py-3.5 font-extrabold text-white shadow-lg shadow-blue-200">지도에서 찾기 <ArrowRight size={18} /></button><button onClick={() => onNavigate('list')} className="rounded-xl border border-slate-300 bg-white px-5 py-3.5 font-extrabold text-slate-700">전체 의자 보기</button></div><div className="mt-8 flex gap-5 text-sm text-slate-500"><span className="flex items-center gap-2"><ShieldCheck size={17} className="text-teal-600" />직접 확인한 정보</span><span className="flex items-center gap-2"><MapPinned size={17} className="text-teal-600" />6곳의 휴식 자리</span></div></div><button onClick={() => onOpenMap(featured)} className="soft-card group overflow-hidden text-left"><ChairImage src={featured.image} alt="로비 창가 의자 대표 사진" className="h-72 w-full md:h-[390px]" /><div className="p-5"><div className="mb-2 text-xs font-bold text-[#0d9c9a]">오늘의 추천 휴식 공간</div><div className="flex items-center justify-between"><div><h2 className="text-xl font-extrabold">{featured.name}</h2><p className="mt-1 text-sm text-slate-500">{featured.building} · {featured.floor}</p></div><span className="grid h-10 w-10 place-items-center rounded-full bg-blue-50 text-[#1668c7] transition group-hover:translate-x-1"><ArrowRight size={18} /></span></div></div></button></section><section className="border-y border-slate-200 bg-white"><div className="container grid gap-6 py-10 sm:grid-cols-3"><Info icon={<MapPinned />} title="건물·층별 탐색" text="익숙한 약도 위에서 위치를 확인해요." /><Info icon={<ShieldCheck />} title="필요한 정보 한눈에" text="좌석 수와 편의시설을 미리 확인해요." /><Info icon={<Compass />} title="방문객을 위한 안내" text="큰 글씨와 쉬운 조작으로 만들었어요." /></div></section><Footer /></main> }
function Info({ icon, title, text }: { icon: React.ReactNode; title: string; text: string }) { return <div className="flex gap-4"><div className="text-[#1668c7]">{icon}</div><div><h3 className="font-extrabold">{title}</h3><p className="mt-1 text-sm text-slate-500">{text}</p></div></div> }
function About() { return <main className="container py-14"><div className="soft-card max-w-3xl p-7 md:p-12"><p className="mb-3 text-sm font-bold text-[#0d9c9a]">ABOUT THIS PROJECT</p><h1 className="text-3xl font-extrabold">프로젝트 소개</h1><p className="mt-6 leading-8 text-slate-600">‘숨은 의자 찾기’는 삼성서울병원 방문객이 병원 안에서 잠시 쉴 수 있는 의자를 쉽게 찾도록 돕는 학생 프로젝트입니다. 병원 공식 홈페이지의 소스코드나 디자인을 복제하지 않고, 자체 제작 약도와 임시 데이터로 구성한 비공식 안내 서비스입니다.</p><div className="mt-8 rounded-xl bg-blue-50 p-5 text-sm leading-6 text-blue-900">사진과 위치 정보는 추후 직접 촬영·확인한 자료로 교체할 수 있도록 분리되어 있습니다. 실제 이용 시에는 현장 안내 표지와 병원 직원의 안내를 함께 확인해 주세요.</div></div></main> }
function Footer() { return <footer className="border-t border-slate-200 bg-white"><div className="container py-7 text-xs leading-6 text-slate-500"><strong className="text-slate-700">숨은 의자 찾기</strong><br />본 서비스는 삼성서울병원의 공식 웹사이트가 아닌 학생 프로젝트로 제작된 비공식 의자 위치 안내 서비스입니다.<br />실제 위치와 운영 상황은 현장에서 달라질 수 있으니 이용 전 확인해 주세요.</div></footer> }
