'use client';
import { useMemo, useState } from 'react';
import { Armchair, Cable, MapPin, Search, Volume2 } from 'lucide-react';
import { Chair } from '@/types/chair';
import ChairImage from './ChairImage';

export default function ChairList({ chairs, onOpenMap }: { chairs: Chair[]; onOpenMap: (chair: Chair) => void }) {
  const [building, setBuilding] = useState('전체 건물'); const [feature, setFeature] = useState('전체 조건'); const [query, setQuery] = useState('');
  const filtered = useMemo(() => chairs.filter(c => (building === '전체 건물' || c.building === building) && (feature === '전체 조건' || (feature === '등받이 있음' && c.hasBackrest) || (feature === '콘센트 있음' && c.hasOutlet) || (feature === '조용한 공간' && c.isQuiet)) && `${c.name} ${c.location}`.includes(query)), [chairs, building, feature, query]);
  return <div className="container py-8"><div className="mb-7"><p className="mb-2 text-sm font-bold text-[#0d9c9a]">CHAIR DIRECTORY</p><h1 className="text-3xl font-extrabold tracking-tight md:text-4xl">의자 목록</h1><p className="mt-3 text-slate-600">필요한 조건에 맞는 휴식 공간을 빠르게 찾아보세요.</p></div><div className="soft-card mb-6 flex flex-wrap gap-3 p-4"><label className="relative min-w-[220px] flex-1"><Search className="absolute left-3 top-3 text-slate-400" size={18} /><input value={query} onChange={e => setQuery(e.target.value)} placeholder="의자 이름이나 위치 검색" className="w-full rounded-lg border border-slate-200 py-2.5 pl-10 pr-3 text-sm outline-none focus:border-blue-500" /></label><select value={building} onChange={e => setBuilding(e.target.value)} className="rounded-lg border border-slate-200 px-3 py-2 text-sm"><option>전체 건물</option><option>본관</option><option>별관</option><option>암병원</option><option>양성자치료센터</option></select><select value={feature} onChange={e => setFeature(e.target.value)} className="rounded-lg border border-slate-200 px-3 py-2 text-sm"><option>전체 조건</option><option>등받이 있음</option><option>콘센트 있음</option><option>조용한 공간</option></select></div><p className="mb-4 text-sm font-bold text-slate-500">총 {filtered.length}개의 의자</p><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{filtered.map(chair => <button key={chair.id} onClick={() => onOpenMap(chair)} className="soft-card overflow-hidden text-left transition hover:-translate-y-1 hover:shadow-lg"><ChairImage src={chair.image} alt={`${chair.name} 사진`} className="h-44 w-full" /><div className="p-4"><div className="mb-2 flex items-center gap-1 text-xs font-bold text-[#0d9c9a]"><MapPin size={13} />{chair.building} · {chair.floor}</div><h2 className="font-extrabold">{chair.name}</h2><p className="mt-1 line-clamp-1 text-sm text-slate-500">{chair.location}</p><div className="mt-4 flex flex-wrap gap-2 text-xs font-bold text-slate-600"><span className="flex items-center gap-1 rounded-full bg-slate-100 px-2 py-1"><Armchair size={13} /> {chair.seatCount}석</span>{chair.hasBackrest && <span className="rounded-full bg-slate-100 px-2 py-1">등받이</span>}{chair.hasOutlet && <span className="flex items-center gap-1 rounded-full bg-slate-100 px-2 py-1"><Cable size={13} /> 콘센트</span>}{chair.isQuiet && <span className="flex items-center gap-1 rounded-full bg-teal-50 px-2 py-1 text-teal-700"><Volume2 size={13} /> 조용함</span>}</div></div></button>)}</div>{filtered.length === 0 && <div className="soft-card p-12 text-center text-slate-500">조건에 맞는 의자가 없습니다.</div>}</div>;
}
