'use client';
import { FormEvent, useState } from 'react';
import { Bot, Loader2, MapPin, MessageCircle, Send, X } from 'lucide-react';
import { chairs } from '@/data/chairs';
import { Chair } from '@/types/chair';

type ChatResult = { answer: string; matchedSpotIds: string[]; found: boolean };

export default function RestChatbot({ onOpenMap }: { onOpenMap: (chair: Chair) => void }) {
  const [open, setOpen] = useState(false); const [question, setQuestion] = useState(''); const [loading, setLoading] = useState(false);
  const [messages, setMessages] = useState<ChatResult[]>([{ answer: '병원 안에서 쉴 곳을 찾아드릴게요. 건물, 층, 근처 시설과 함께 질문해 주세요.', matchedSpotIds: [], found: false }]);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!question.trim() || loading) return; const value = question.trim(); setQuestion(''); setLoading(true); try { const response = await fetch('/api/chat', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ question: value }) }); const data = await response.json(); setMessages((prev) => [...prev, response.ok ? data : { answer: data.error || '질문을 처리할 수 없어요.', matchedSpotIds: [], found: false }]); } catch { setMessages((prev) => [...prev, { answer: '챗봇 연결에 잠시 문제가 생겼어요.', matchedSpotIds: [], found: false }]); } finally { setLoading(false); } };
  return <><button onClick={() => setOpen(true)} className="fixed bottom-5 right-5 z-40 flex items-center gap-2 rounded-full bg-[#1668c7] px-4 py-3 font-extrabold text-white shadow-xl shadow-blue-200" aria-label="휴식 공간 안내 챗봇 열기"><MessageCircle size={20} /> <span className="hidden sm:inline">휴식 공간 챗봇</span></button>{open && <div className="fixed bottom-5 right-5 z-50 flex h-[min(620px,calc(100vh-40px))] w-[min(390px,calc(100vw-28px))] flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl"><div className="flex items-center justify-between bg-[#18324a] p-4 text-white"><div className="flex items-center gap-3"><span className="grid h-9 w-9 place-items-center rounded-full bg-white/15"><Bot size={20} /></span><div><strong className="block">숨은 휴식공간 챗봇</strong><span className="text-xs text-slate-300">등록된 데이터만 바탕으로 안내해요</span></div></div><button onClick={() => setOpen(false)} aria-label="챗봇 닫기"><X size={20} /></button></div><div className="flex-1 space-y-4 overflow-y-auto bg-slate-50 p-4">{messages.map((message, index) => <div key={index} className="space-y-2"><div className="max-w-[92%] rounded-2xl rounded-tl-sm bg-white p-3 text-sm leading-6 text-slate-700 shadow-sm">{message.answer}</div>{message.found && message.matchedSpotIds.length > 0 && <div className="space-y-2">{message.matchedSpotIds.map((id) => { const chair = chairs.find((item) => item.id === id); return chair ? <button key={id} onClick={() => onOpenMap(chair)} className="flex w-full items-center gap-2 rounded-xl border border-blue-100 bg-blue-50 p-3 text-left text-xs font-bold text-blue-900"><MapPin size={16} className="shrink-0 text-[#1668c7]" /><span>{chair.building} {chair.floor} · {chair.name}<small className="mt-1 block font-normal text-blue-700">지도로 위치 보기</small></span></button> : null; })}</div>}</div>) }{loading && <div className="flex items-center gap-2 text-sm text-slate-500"><Loader2 size={16} className="animate-spin" />찾아보고 있어요...</div>}</div><form onSubmit={submit} className="flex gap-2 border-t bg-white p-3"><input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="예: 본관 1층에 쉴 곳 있어요?" className="min-w-0 flex-1 rounded-xl border border-slate-200 px-3 py-2.5 text-sm outline-none focus:border-blue-500" aria-label="휴식 공간 질문" /><button type="submit" disabled={loading || !question.trim()} className="grid h-11 w-11 shrink-0 place-items-center rounded-xl bg-[#1668c7] text-white disabled:bg-slate-300" aria-label="질문 보내기"><Send size={17} /></button></form></div>}</>;
}
